=== jason80/dragonfly/templates/dragonfly.dtd
<!ELEMENT dragonfly ANY>

<!-- Property -->
<!ELEMENT property (#PCDATA)>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #REQUIRED>

<!-- Include -->
<!ELEMENT include (#PCDATA)>
<!ATTLIST include path CDATA #REQUIRED>

<!-- Game -->
<!ELEMENT game (#PCDATA)>
<!ATTLIST game title CDATA #REQUIRED>
<!ATTLIST game author CDATA #REQUIRED>

<!-- Verb -->
<!ELEMENT verb ANY>
<!ATTLIST verb names CDATA #REQUIRED>
<!ATTLIST verb action CDATA #REQUIRED>
<!ATTLIST verb syntax CDATA #IMPLIED>
<!ELEMENT response (#PCDATA)>
<!ATTLIST response id CDATA #IMPLIED>
<!ATTLIST response string CDATA #IMPLIED>
<!ATTLIST response class CDATA #IMPLIED>
<!ATTLIST response style CDATA #IMPLIED>
<!ATTLIST response new-line (true|false) "true">
<!ATTLIST response instance CDATA #IMPLIED>
<!ATTLIST response set CDATA #IMPLIED>
<!ATTLIST response unset CDATA #IMPLIED>
<!ATTLIST response name CDATA #IMPLIED>
<!ATTLIST response destiny CDATA #IMPLIED>
<!ATTLIST response exit CDATA #IMPLIED>

<!-- Article -->
<!ELEMENT article (#PCDATA)>
<!ATTLIST article name CDATA #REQUIRED>
<!ATTLIST article genre CDATA #REQUIRED>
<!ATTLIST article number CDATA #REQUIRED>
<!ATTLIST article indefinited (true|false) "true">

<!-- Exit -->
<!ELEMENT exit (#PCDATA)>
<!ATTLIST exit names CDATA #REQUIRED>

<!-- Noun -->
<!ELEMENT noun ANY>
<!ATTLIST noun names CDATA #REQUIRED>
<!-- Set -->
<!ELEMENT set (#PCDATA)>
<!-- Variable -->
<!ELEMENT variable (#PCDATA)>
<!ATTLIST variable name CDATA #REQUIRED>
<!ATTLIST variable value CDATA #REQUIRED>
<!-- Events -->
<!ELEMENT after ANY>
<!ATTLIST after actions CDATA #REQUIRED>
<!ATTLIST after cancel (true|false) "true">
<!ELEMENT before ANY>
<!ATTLIST before actions CDATA #REQUIRED>
<!ATTLIST before cancel (true|false) "true">
<!-- Conditions -->
<!ELEMENT if (#PCDATA)>
<!ATTLIST if class CDATA #REQUIRED>
<!ATTLIST if instance CDATA #IMPLIED>
<!ATTLIST if attr CDATA #IMPLIED>
<!ATTLIST if exit CDATA #IMPLIED>
<!ATTLIST if container CDATA #IMPLIED>
<!-- Connection -->
<!ELEMENT connection (#PCDATA)>
<!ATTLIST connection exit CDATA #REQUIRED>
<!ATTLIST connection destiny CDATA #REQUIRED>

=== jason80/dragonfly/samples/bosque/dragonfly.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dragonfly SYSTEM "../../templates/dragonfly.dtd">

<dragonfly>
	<include path="../../templates/dict-debug.xml" />
	<include path="../../templates/dict-es.xml" />

	<include path="claro.xml" />
	<include path="naranja.xml" />
	<include path="rio.xml" />
	<include path="casa-afuera.xml" />
	<include path="casa-adentro.xml" />

	<game title="En El Bosque" author="Javier Candales (Jasón)" />
	<property name="player" value="jugador" />
	<property name="look-around" value="always" />


</dragonfly>

=== jason80/dragonfly/samples/bosque/casa-afuera.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dragonfly SYSTEM "../../templates/dragonfly.dtd">

<dragonfly>
	<noun names="La Cabaña, casa-afuera">
		<after actions="LookAround">
			Una misteriosa cabaña se presenta en la escena, y el camino continua hacia el norte. Por el sur se vuelve al río.
		</after>

		<noun names="cabaña, casa, casita, rancho">
			<set>female, fixed, scene</set>

			<after actions="ExamineObject">
				La torcida cabaña de troncos está a un lado del sendero, tiene una puerta pero carece de ventanas.
			</after>
		</noun>

		<noun names="puerta, porton, puerta-afuera">
			<set>female, fixed, scene, closable, closed</set>

			<after actions="ExamineObject">
				<if class="IsSet" instance="puerta-afuera" attr="closed" />
				La puerta es de madera y está cerrada.
			</after>

			<after actions="ExamineObject">
				<if class="IsNotSet" instance="puerta-afuera" attr="closed" />
				La puerta es de madera y está abierta.
			</after>

			<!--<before actions="OpenObject, OpenWith, PushObject, PullObject" cancel="true">
				No se abre, debe estar atrancada.
			</before>-->
			<after actions="OpenObject">
				<response class="Attr" instance="puerta-adentro" unset="closed" />
			</after>

			<after actions="CloseObject">
				<response class="Attr" instance="puerta-adentro" set="closed" />
			</after>
			
			<before actions="TouchObject, HitObject" cancel="true">
				Nadie responde.
			</before>

		</noun>

		<before actions="GoTo" cancel="true">
			<if class="DirectEqualsExit" exit="adentro" />
			<if class="IsSet" attr="closed" instance="puerta-afuera" />
			La puerta está cerrada.
		</before>

		<connection exit="sur" destiny="orilla-rio"/>
		<connection exit="norte" destiny="claro" />
		<connection exit="adentro" destiny="casa-adentro" />
	</noun>
</dragonfly>

=== jason80/dragonfly/samples/bosque/rio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dragonfly SYSTEM "../../templates/dragonfly.dtd">

<dragonfly>
	<noun names="A La Orilla del Río, orilla-rio">
		<after actions="LookAround">
			El sendero continua hacia la orilla de un río, luego dobla hacia el norte.
		</after>

		<clone instance="sendero-principal" />
		<clone instance="arboles-principal" />

		<noun names="río, orilla, agua, arroyo">
			<set>fixed, scene</set>
			<after actions="ExamineObject">
				Con un torrente bastante fuerte, el ancho río se complica para cruzar.
			</after>
		</noun>

		<connection exit="oeste" destiny="arbol-naranja" />
		<connection exit="norte" destiny="casa-afuera" />
	</noun>
</dragonfly>

=== jason80/dragonfly/samples/menu-objetos/dragonfly.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE dragonfly SYSTEM "../../templates/dragonfly.dtd">
<dragonfly>
	<!-- En Dragonfly pueden haber dos objetos con el mismo nombre.
		Ejemplo:
		Cuando el jugador examine un objeto, pero en el lugar o inventario
		exiten dos con ese nombre, el motor preguntará a qué objeto se refiere. -->

	<game title="Prueba De Objetos" author="Javier Candales (Jasón)"></game>

	<include path="../../templates/dict-es.xml"></include>
	<include path="../../templates/dict-debug.xml"></include>

	<property name="player" value="jugador"></property>
	<property name="look-around" value="always"></property>

	<noun names="En Algún Lugar">
		<after actions="LookAround">
			Estás en una habitación blanca que sirve para hacer ensayos.
		</after>

		<!-- Cuando el jugador escriba "recoger bola", Dragonfly detectará que
			hay dos objetos con el nombre "bola". Un menú de selección se mostrará -->
		<noun names="bola roja, bola">
			<set>female</set>
			<after actions="ExamineObject">
				Una bola de color rojo.
			</after>
		</noun>

		<noun names="bola verde, bola">
			<set>female</set>
			<after actions="ExamineObject">
				Una bola de color verde.
			</after>
		</noun>

		<noun names="jugador"></noun>
	</noun>
</dragonfly>

=== jason80/dragonfly/samples/la-casa/living.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE dragonfly SYSTEM "../../templates/dragonfly.dtd">
<dragonfly>
	<!-- En Dragonfly los sustantivos son los objetos del juego: los lugares,
			los diferentes objetos, el jugador, etc. son Nouns. -->
	<!-- Por lo tanto Nouns = Objetos -->
	<!-- Los objetos tienen la propiedad multinombre y "responden" a cada uno 
		de esos nombres. Generalmente, el primer nombre es mas importante porque 
		es el nombre que se muestra. Igualmente, todos los nombres le dan identidad
		al objeto. -->
	<noun names="El Living, living">
		<!-- Descripción: -->
		<!-- DESPUÉS de "mirar alrededor". -->
		<after actions="LookAround">
			<!-- Responder con un mensaje: -->
			En éste lugar puedes encontrar una pequeña mesa rodeada de sillones. Hacia el norte se encuentra el dormitorio y al oeste está la cocina.
			<response class="Pause"></response>
			hola
			
		</after>

		<!-- Los mensajes son respuestas de tipo Message. Lo anterior es una forma de
			mostrar un mensaje, pero Dragonfly detecta que es un "response".
			Se puede hacer de forma explícita de la siguiente manera:
		<after actions="LookAround">
			<response class="Message">
				En éste lugar puedes encontrar una pequeña mesa rodeada de sillones.
			</response>
		</after>
		-->


		<!-- Los sillones y la mesa son objetos que están dentro del living -->
		<!-- El jugador se puede referir al objeto con los diferentes nombres: -->
		<noun names="sillones, sillon, silla">
			<!-- Con set se puede establecer atributos al objeto -->
			<!-- son "los sillones" asi que el objeto es plural -->
			<!-- es "la mesa" entonces es femenino (female) -->
			<!-- fixed: el jugador no podrá llevarse el objeto -->
			<!-- scene: significa que el objeto pertenece a la escena y no
				se mostrará automáticamente al "mirar alrededor"-->
			<set>plural, fixed, scene</set>
			
			<!--Descripción:
				Cuando el jugador EXAMINE el objeto MOSTRAR el mensaje -->
			<after actions="ExamineObject">
				Son cuatro sillas de madera de pino.
			</after>
		</noun>
		<noun names="mesita, tabla, mesa">
			<set>female, fixed, scene</set>
			<after actions="ExamineObject">
				La mesita de caoba está en el centro del living.
			</after>
		</noun>

		<!-- No puede faltar el jugador dentro del living. Cualquier objeto
			en Dragonfly podría ser el jugador. Hay que establecer cuál es con
			la propiedad "player" como se hace en el archivo "dragonfly.xml" -->
		<noun names="jugador, player" />

		<!-- Hacia el norte hay un dormitorio.
			"connection" asocia una "salida" con un objeto destino. Ese
			destino es el dormitorio que está definido en "dormitorio.xml" y la salida
			es "norte". -->
		<!-- El jugador podrá trasladarse al dormitorio con solo escribir
			"ir hacia el norte" o simplemente "norte" -->
		<connection exit="norte" destiny="dormitorio" />
		<connection exit="oeste" destiny="cocina" />
	</noun>
</dragonfly>

=== jason80/dragonfly/templates/dict-es.xml
<?xml version = "1.0" encoding = "UTF-8" ?>

<!DOCTYPE dragonfly SYSTEM "https://raw.githubusercontent.com/jason80/dragonfly/main/templates/dragonfly.dtd">

<dragonfly>

	<!--VERBS-->
	<verb names = "?" action = "UnknownVerb">
		<response id = "unknown-verb" string = "No se lo que estás diciendo." />
	</verb>

	<verb names = "fin, finalizar, finaliza, terminar, termina, final, acaba, acabar, concluye, concluir, quit, q"
			action = "Quit">
			<response id="syntax-fail" string="Solo escribe 'fin' para salir." />
	</verb>

	<verb names = "limpiar, borrar, limpia, borra, clear, cls" action = "Clear" />

	<!--TODO: LOAD, SAVE-->

	<verb names = "inventario, i, inv" action = "Inventory">
		<response id = "inventory-is-empty" string = "No tienes nada en tu poder." />
		<response id = "syntax-fail" string = "Escribe 'inventario' o 'i' para saber lo que llevas." />
	</verb>

	<verb names = "examinar, examina, mirar, mira, busca, buscar, revisa, revisar, x, m"
			action = "LookInside" syntax = "en/dentro/adentro, 1">
		<response id = "direct-not-found" string = "No encuentro eso." />
		<response id = "direct-is-the-player" string = "Puedes probar con: inventario ó i." />
		<response id = "direct-is-not-container" string = "No puedes ver adentro de #1." />
		<response id = "direct-is-closed" string = "#^1 est@1(á,á,án,án) cerrad@1(o,a,os,as)." />
		<response id = "container-is-empty" string = "No hay nada en #1." />
	</verb>

	<verb names = "examinar, examina, mirar, mira, x, m"
			action = "ExamineObject" syntax = "1">
		<response id = "direct-not-found" string = "No hay eso." />
	</verb>

	<verb names = "examinar, examina, mirar, mira, ver, x, m"
			action = "LookAround" />

	<verb names = "toma, tomar, agarra, agarrar, recoger, recoge, coge, coger, junta, juntar, obtener, obtiene, sustrae, sustraer, sacar, saca, extrae, estraer"
		syntax = "1, de/desde/del, 2" action = "TakeFrom">

		<response id = "indirect-not-found" string = "No se de dónde lo quieres sacar." />
		<response id = "indirect-is-not-container" string = "No se puede sacar cosas de #2." />
		<response id = "indirect-is-closed" string = "Est@2(á,á,án,án) cerrad@2(o,a,os,as)." />
		<response id = "direct-not-found" string = "#^2 no contiene eso." />
		<response id = "direct-taken" string = "Sacas #1 de #2." />
		<response id = "syntax-fail" string = "Tienes que indicar qué quieres sacar." />

	</verb>

	<verb names = "tomar, toma, agarrar, agarra, recoger, recoge, coger, coge, juntar, junta, obtener, obtiene"
		syntax = "1" action = "TakeObject">
		<response id = "direct-not-found" string = "No hay eso." />
		<response id = "direct-is-the-player" string = "No puedes llevarte a ti mismo." />
		<response id = "direct-is-fixed" string = "No puedes llevarte #1" />
		<response id = "direct-is-heavy" string = "#^1 @1(es,es,son,son) muy pesad@1(o,a,os,as) como para que te @1(lo,la,los,las) lleves." />
		<response id = "direct-taken" string = "Recoges #1." />
	</verb>

	<verb names = "dejar, deja, soltar, suelta, olvidar, olvida, poner, pon, insertar, inserta, colocar, coloca, situar, situa"
		syntax = "1, en/dentro/adentro/dentro de/adentro de, 2" action = "LeaveIn">
		<response id = "indirect-not-found" string = "¿A dónde?" />
		<response id = "direct-not-found" string = "No tienes eso." />
		<response id = "direct-is-the-player" string = "¿Meterte eso?" />
		<response id = "indirect-is-not-container" string = "No puedes meter #1 en #2." />
		<response id = "indirect-is-closed" string = "#^2 est@2(á,á,án,án) cerrad@1(o,a,os,as)." />
		<response id = "direct-leaved" string = "Dejas #1 en #2." />
		<response id = "syntax-fail" string = "Tienes que decir que quieres dejar." />
	</verb>

	<verb names = "ir, ve, anda, irse" action = "GoTo"
		syntax = "a/al/hacia, 1">
		<response id = "exit-not-exists" string = "¿A dónde?" />
		<response id = "exit-not-found" string = "No puedes ir por ahí." />
	</verb>

	<verb names = "tirar, tira" action = "PullObject"
		syntax = "de/del, 1">
		<response id = "direct-not-found" string = "No existe eso." />
		<response id = "direct-is-the-player" string = "Tirar de ti mismo ..." />
		<response id = "direct-is-fixed" string = "No puedes tirar de #1." />
		<response id = "nothing-happens" string = "Tirando de #1, no ocurre nada." />
		<response id = "syntax-fail" string = "No se que jalar." />
	</verb>

	<verb names = "dejar, tirar, deja, tira" action = "LeaveObject"
			syntax = "1">
		<response id = "direct-not-found" string = "No tienes eso." />
		<response id = "direct-left" string = "Lo dejas" />
	</verb>

	<verb names = "abrir, abre" action = "OpenWith"
			syntax = "1, con/mediante, 2">
		<response id = "direct-not-found" string = "Eso que quieres abrir no existe." />
		<response id = "indirect-not-found" string = "No tienes eso para abrir." />
		<response id = "direct-is-the-player" string = "No puedes abrirte a ti mismo." />
		<response id = "indirect-is-the-player" string = "No eres una llave." />
		<response id = "direct-is-not-closable" string = "No se puede abrir #1" />
		<response id = "direct-is-open" string = "#^1 ya est@1(á,án,á,án) abiert@1(o,a,os,as)." />
		<response id = "nothing-happens" string = "No puedes abrir #1 con eso." />
		<response id = "syntax-fail" string = "Prueba con 'abrir objeto' o 'abrir objeto con otro'." />
	</verb>

	<verb names = "cerrar, cierra" action = "CloseWith"
			syntax = "1, con/mediante, 2">
		<response id = "direct-not-found" string = "Eso que quieres cerrar no existe." />
		<response id = "indirect-not-found" string = "No tienes eso para cerrar." />
		<response id = "direct-is-the-player" string = "No puedes cerrarte a ti mismo." />
		<response id = "indirect-is-the-player" string = "No eres una llave." />
		<response id = "direct-is-not-closable" string = "No se puede cerrar #1" />
		<response id = "direct-is-closed" string = "#^1 ya est@1(á,án,á,án) cerrad@1(o,a,os,as)." />
		<response id = "nothing-happens" string = "No puedes cerrar #1 con eso." />
		<response id = "syntax-fail" string = "Prueba con 'cerrar objeto' o 'cerrar objeto con otro'." />
	</verb>

	<verb names = "abrir, abre" action = "OpenObject"
			syntax = "1">
		<response id = "direct-not-found" string = "No hay eso para abrir." />
		<response id = "direct-is-the-player" string = "No puedes abrirte a ti mismo." />
		<response id = "direct-is-not-closable" string = "No se puede abrir #1." />
		<response id = "direct-is-open" string = "#^1 ya est@1(á,án,á,án) abiert@1(o,a,os,as)." />
		<response id = "direct-was-opened" string = "Abres #1." />
	</verb>

	<verb names = "cerrar, cierra" action = "CloseObject"
			syntax = "1">
		<response id = "direct-not-found" string = "No hay eso para cerrar." />
		<response id = "direct-is-the-player" string = "No puedes cerrarte a ti mismo." />
		<response id = "direct-is-not-closable" string = "No se puede cerrar #1." />
		<response id = "direct-is-closed" string = "#^1 ya est@1(á,án,á,án) cerrad@1(o,a,os,as)." />
		<response id = "direct-was-closed" string = "Cierras #1." />
	</verb>

	<verb names = "jala, jalar" action = "PullObject"
		syntax = "1">
		<response id = "direct-not-found" string = "No existe eso." />
		<response id = "direct-is-the-player" string = "Tirar de ti mismo." />
		<response id = "direct-is-fixed" string = "No puedes tirar de #1." />
		<response id = "nothing-happens" string = "Tirando de #1, no ocurre nada." />
		<response id = "syntax-fail" string = "No se que jalar." />
	</verb>

	<verb names = "empuja, empujar, mover, mueve, desplaza, desplazar" action = "PushObject"
		syntax = "1">
		<response id = "direct-not-found" string = "Eso que quieres empujar no está." />
		<response id = "direct-is-the-player" string = "No puedes empujarte a ti mismo." />
		<response id = "direct-is-fixed" string = "#^1 est@1(á,án,á,án) fij@1(o,a,os,as)." />
		<response id = "nothing-happens" string = "No ocurre nada cuando empujas #1." />
		<response id = "syntax-fail" string = "No se que empujar." />
	</verb>

	<verb names="fuma, fumar, pita, pitar" action="SmokeObject"
		syntax="1">
		<response id="direct-not-found" string="No hay eso."/>
		<response id="direct-is-the-player" string="No tienes pinta de cigarrillos."/>
		<response id="nothing-happens" string="No tiene sentido hacer eso."/>
	</verb>

	<verb names="encender, enciende, prender, prende" action="TurnOnObject"
		syntax="1">
		<response id="direct-not-found" string="No hay eso que encender."/>
		<response id="direct-is-the-player" string="No eres una linterna."/>
		<response id="nothing-happens" string="No se puede encender eso."/>
	</verb>

	<verb names="apagar, apaga" action="TurnOffObject"
		syntax="1">
		<response id="direct-not-found" string="No hay eso que apagar."/>
		<response id="direct-is-the-player" string="No eres una linterna."/>
		<response id="nothing-happens" string="No se puede apagar eso."/>
	</verb>

	<!--ARTICLES-->
	<article name = "el" genre = "male" number = "singular" indefinited = "false" />
	<article name = "la" genre = "female" number = "singular" indefinited = "false" />
	<article name = "los" genre = "male" number = "plural" indefinited = "false" />
	<article name = "las" genre = "female" number = "plural" indefinited = "false" />

	<article name = "un" genre = "male" number = "singular" indefinited = "true" />
	<article name = "una" genre = "female" number = "singular" indefinited = "true" />
	<article name = "unos" genre = "male" number = "plural" indefinited = "true" />
	<article name = "unas" genre = "female" number = "plural" indefinited = "true" />

	<!--EXITS-->
	<exit names = "norte, n" />
	<exit names = "sur, s" />
	<exit names = "este, e" />
	<exit names = "oeste, o, w" />

	<exit names = "noreste, ne" />
	<exit names = "noroeste, no, nw" />
	<exit names = "sudeste, sureste, se" />
	<exit names = "sudoeste, suroeste, so, sw" />

	<exit names = "arriba, arr" />
	<exit names = "abajo, aba" />
	<exit names = "adentro, ad" />
	<exit names = "afuera, af" />

</dragonfly>

=== jason80/dragonfly/samples/bosque/casa-adentro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dragonfly SYSTEM "../../templates/dragonfly.dtd">

<dragonfly>
	<noun names="Dentro de La Cabaña, casa-adentro">
		<after actions="LookAround">
			Es una posilga. Hay estanterias llenas de frascos, mesas repletas de ingredientes indescriptibles. En el centro, un grán caldero.
			<response class="Message">
				Detrás tuyo está la puerta que te lleva afuera.
			</response>
		</after>

		<after actions="LookAround">
			<if class="Contains" container="casa-adentro" instance="bruja" />
			Una bruja está junto al caldero.
		</after>
		<!-- Puerta -->
		<noun names="puerta, porton, puerta-adentro">
			<set>female, fixed, scene, closable, closed</set>

			<after actions="ExamineObject">
				<if class="IsSet" instance="puerta-adentro" attr="closed" />
				La puerta es de madera y está cerrada.
			</after>

			<after actions="ExamineObject">
				<if class="IsNotSet" instance="puerta-adentro" attr="closed" />
				La puerta es de madera y está abierta.
			</after>

			<after actions="OpenObject">
				<response class="Attr" instance="puerta-afuera" unset="closed" />
			</after>

			<after actions="CloseObject">
				<response class="Attr" instance="puerta-afuera" set="closed" />
			</after>
			
			<before actions="TouchObject, HitObject" cancel="true">
				¡Ya estás adentro!
			</before>
		</noun>

		<!-- Caldero -->
		<noun names="caldero, olla, liquido, fuego">
			<set>heavy, scene</set>
			<after actions="ExamineObject">
				Un líquido burbujeante se está cocinando en el gran caldero de metal.
			</after>

			<before actions="PushObject, PullObject, TouchObject"
						cancel="true">
				Ni de broma, está caliente.
			</before>
		</noun>

		<!-- Cosas -->
		<noun names="bienes de la bruja, estanterias, estanteria, frascos, frasco, ingredientes, ingrediente, mesa, mesas">
			<set>plural, fixed, scene</set>
			<after actions="ExamineObject">
				Es interminable la cantidad de cosas, es inútil ahondar en ellas.
			</after>
		</noun>

		<!-- La bruja -->
		<noun names="bruja">
			<set>female, fixed, speaker, scene</set>
			<after actions="ExamineObject">
				La arapienta bruja está removiendo el contenido del caldero.
				<response class="TipOnce" instance="bruja">
					Dile algo a la bruja con: 'habla a la bruja: hola'
				</response>
			</after>

			<after actions="TalkTo" cancel="true">
				
			</after>
		</noun>

		<before actions="GoTo" cancel="true">
			<if class="DirectEqualsExit" exit="afuera" />
			<if class="IsSet" attr="closed" instance="puerta-afuera" />
			La puerta está cerrada.
		</before>

		<connection exit="afuera" destiny="casa-afuera" />
	</noun>
</dragonfly>

=== jason80/dragonfly/samples/la-casa/cocina.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE dragonfly SYSTEM "../../templates/dragonfly.dtd">
<dragonfly>

	<!-- En eśta sala está la puerta de salida. Si el jugador consigue abrirla y
		salir por el oeste, gana el juego. -->
	<noun names="La Cocina, cocina">
		<after actions="LookAround">
			Una ámplia sala rodeada de mesadas, mecheros, y un horno. Por el éste se vuelve al living y en el oeste está la puerta de salida.
		</after>

		<noun names="mesadas, mesada, mechero, mecheros, hornalla, hornallas">
			<set>female, plural, fixed, scene</set>

			<after actions="ExamineObject">
				Las mesadas, mecheros y el horno conforman la cocina y no tienen nada de interesante.
			</after>
		</noun>

		<noun names="horno">
			<set>fixed, scene, container</set>

			<after actions="ExamineObject">
				Un grán horno se encuentra entre las mesadas.
			</after>
		</noun>

		<!-- 
			La puerta de salida
		-->
		<noun names="puerta, puerta de salida, salida, oeste">
			<set>female, closable, closed, scene, con-llave</set>
			<!-- 
				closable: el objeto responde a "abrir" y "cerrar"
				closed: inicialmente está cerrado
				con-llave: un atributo personalizado para indicar que está con llave.
			-->

			<!-- Descripción de la puerta -->
			<after actions="ExamineObject">
				La puerta es de madera y da al exterior de la casa.
			</after>

			<!-- ANTES de ABRIR puerta, CANCELAR ...-->
			<before actions="OpenObject" cancel="true">
				<!-- Si la puerta está "con llave" -->
				<if class="IsSet" instance="puerta" attr="con-llave" />
				La puerta está cerrada con llave.
			</before>

			<!-- ANTES de ABRIR la puerta CON algo que no sea la llave, CANCELAR ...-->
			<before actions="OpenWith" cancel="true">
				<!-- Objeto indirecto no es la llave-->
				<if class="IndirectNotEquals" instance="llave" />
				No puedes abrir la puerta con eso.
			</before>

			<!-- ANTES de ABRIR la puerta CON la llave, CANCELAR -->
			<before actions="OpenWith" cancel="true">
				<!-- Si el objeto indirecto es la llave y ...-->
				<if class="IndirectEquals" instance="llave" />
				<!-- Si la puerta está "con llave" -->
				<if class="IsSet" instance="puerta" attr="con-llave"/>
				Abres la puerta con la llave.
				<!-- Abre la puerta y queda sin llave -->
				<response class="Attr" instance="puerta" unset="con-llave, closed" />
			</before>

		</noun>

		<!-- ANTES de IR HACIA, CANCELAR ...-->
		<before actions="GoTo" cancel="true">
			<!-- Hacia el OESTE y ...-->
			<if class="DirectEqualsExit" exit="oeste" />
			<!-- La puerta está cerrada ...-->
			<if class="IsSet" instance="puerta" attr="closed" />
			La puerta está cerrada.
		</before>

		<!-- ANTES de IR HACIA, CANCELAR ...-->
		<before actions="GoTo" cancel="true">
			<!-- Hacia el OESTE y ...-->
			<if class="DirectEqualsExit" exit="oeste" />
			<!-- La puerta NO está cerrada ...-->
			<if class="IsNotSet" instance="puerta" attr="closed" />
			<!-- FIN DEL JUEGO -->
			<response class="EndGame" result="victory">
				Has salido de la casa con éxito.
			</response>
		</before>

		<!-- Conecta el este con El Living -->
		<connection exit="este" destiny="living"></connection>

		<!-- Aunque no exista el lugar "afuera de la casa" se debe 
			crear la conexión "oeste". Siempre se cancelará la acción GoTo
			de todas formas. -->
		<connection exit="oeste" destiny="(afuera)"></connection>
	</noun>
</dragonfly>
