=== jason80/dragonfly/templates/dragonfly.dtd
<!ELEMENT dragonfly ANY>

<!-- Property -->
<!ELEMENT property (#PCDATA)>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #REQUIRED>

<!-- Include -->
<!ELEMENT include (#PCDATA)>
<!ATTLIST include path CDATA #REQUIRED>

<!-- Game -->
<!ELEMENT game (#PCDATA)>
<!ATTLIST game title CDATA #REQUIRED>
<!ATTLIST game author CDATA #REQUIRED>

<!-- Verb -->
<!ELEMENT verb ANY>
<!ATTLIST verb names CDATA #REQUIRED>
<!ATTLIST verb action CDATA #REQUIRED>
<!ATTLIST verb syntax CDATA #IMPLIED>
<!ELEMENT response (#PCDATA)>
<!ATTLIST response id CDATA #IMPLIED>
<!ATTLIST response string CDATA #IMPLIED>
<!ATTLIST response class CDATA #IMPLIED>
<!ATTLIST response style CDATA #IMPLIED>
<!ATTLIST response new-line (true|false) "true">
<!ATTLIST response instance CDATA #IMPLIED>
<!ATTLIST response set CDATA #IMPLIED>
<!ATTLIST response unset CDATA #IMPLIED>
<!ATTLIST response name CDATA #IMPLIED>
<!ATTLIST response destiny CDATA #IMPLIED>
<!ATTLIST response exit CDATA #IMPLIED>

<!-- Article -->
<!ELEMENT article (#PCDATA)>
<!ATTLIST article name CDATA #REQUIRED>
<!ATTLIST article genre CDATA #REQUIRED>
<!ATTLIST article number CDATA #REQUIRED>
<!ATTLIST article indefinited (true|false) "true">

<!-- Exit -->
<!ELEMENT exit (#PCDATA)>
<!ATTLIST exit names CDATA #REQUIRED>

<!-- Noun -->
<!ELEMENT noun ANY>
<!ATTLIST noun names CDATA #REQUIRED>
<!-- Set -->
<!ELEMENT set (#PCDATA)>
<!-- Variable -->
<!ELEMENT variable (#PCDATA)>
<!ATTLIST variable name CDATA #REQUIRED>
<!ATTLIST variable value CDATA #REQUIRED>
<!-- Events -->
<!ELEMENT after ANY>
<!ATTLIST after actions CDATA #REQUIRED>
<!ATTLIST after cancel (true|false) "true">
<!ELEMENT before ANY>
<!ATTLIST before actions CDATA #REQUIRED>
<!ATTLIST before cancel (true|false) "true">
<!-- Conditions -->
<!ELEMENT if (#PCDATA)>
<!ATTLIST if class CDATA #REQUIRED>
<!ATTLIST if instance CDATA #IMPLIED>
<!ATTLIST if attr CDATA #IMPLIED>
<!ATTLIST if exit CDATA #IMPLIED>
<!ATTLIST if container CDATA #IMPLIED>
<!-- Connection -->
<!ELEMENT connection (#PCDATA)>
<!ATTLIST connection exit CDATA #REQUIRED>
<!ATTLIST connection destiny CDATA #REQUIRED>

=== jason80/dragonfly/templates/dict-debug.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE dragonfly SYSTEM "./dragonfly.dtd">

<dragonfly>
	<verb names = "info" action = "dragonfly.debug.Info" syntax = "1" />
	<verb names = "tree" action="dragonfly.debug.TreeObject" syntax="1" />
	<verb names = "tree" action = "dragonfly.debug.Tree"/>
	<verb names = "attr, attribute" action = "dragonfly.debug.Attr"
		syntax = "1, set/unset, 2" />
	<verb names = "move, mv" action = "dragonfly.debug.Move" syntax = "1, to, 2" />
	<verb names = "root" action = "dragonfly.debug.Root" syntax = "1" />
	<verb names = "verb" action="dragonfly.debug.VerbInfo" syntax = "1" />
</dragonfly>

=== jason80/dragonfly/samples/puertas/dragonfly.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE dragonfly SYSTEM "../../templates/dragonfly.dtd">
<dragonfly>
<!--
	En este ejemplo se muestra como crear puertas.
	
	En Dragonfly se pueden colocar objetos dentro de otros, Tenga lógica o no.
	Por ejemplo: una cama, una mesa, o una lámpara estaria dentro de una habitación.

	Pero ocurre algo diferente con las puerta. Se sobreentiende que dos lugares pueden
	compartir una misma puerta. Por ejemplo: una puerta que conecte la habitación con un
	pasillo.

	Resulta que en Dragonfly los objetos no pueden estar en dos lugares al mismo tiempo.
	Entonces, si no puede haber una misma instancia dentro de dos objetos diferentes la
	solución sería crear dos puertas:
-->

	<game title="Ejemplo de Puertas" author="Javier Candales (Jasón)"></game>
	<include path="../../templates/dict-es.xml"></include>
	<include path="../../templates/dict-debug.xml"></include>

	<property name="look-around" value="always"></property>
	<property name="player" value="jugador"></property>


	<!-- Las habitaciones están conectadas de norte a sur y el jugador 
		está en la Habitación A -->
	<noun names="Habitación A, habitacion-a">
		<after actions="LookAround">
			Estás en la habitación A. Al sur puedes ver una puerta.
		</after>

		<noun names="jugador, player"></noun>

		<!-- Ambas puertas comparten los nombres salvo por uno para diferenciarlas -->
		<noun names="puerta, porton, puertita, puerta-ab">
			<!-- Las puertas son "cerrables" y arrancan "cerradas" -->
			<set>female, fixed, scene, closable, closed</set>

			<!-- Pueden ó no compartir la descripción, dependerá de la mecánica del juego-->
			<after actions="ExamineObject">
				Una puerta de madera que me lleva a otra habitación.
			</after>

			<!-- DESPUÉS de abrir la puerta AB ...-->
			<after actions="OpenObject">
				<!-- QUITAR el atributo "closed" a la puerta BA (abrirla) -->
				<!-- De ésta manera, las puertas se mantienen sincronizadas, 
					si el jugador abre una puerta la otra se abre; si cierra
					la puerta, la otra se cierra. -->
				<response class="Attr" instance="puerta-ba" unset="closed"></response>
			</after>

			<!-- DESPUÉS de cerrar la puerta AB-->
			<after actions="CloseObject">
				<!-- CERRAR la puerta BA -->
				<response class="Attr" instance="puerta-ba" set="closed"></response>
			</after>
		</noun>

		<!-- El jugador no podrá ir hacia la habitación B estando la puerta cerrada. -->
		<!-- ANTES de ir hacia el sur, CANCELAR ...-->
		<before actions="GoTo" cancel="true">
			<if class="DirectEqualsExit" exit="sur"></if>

			<!-- SI la puerta AB está cerrada-->
			<if class="IsSet" instance="puerta-ab" attr="closed"></if>

			<!-- Informa que la puerta está cerrada. -->
			La puerta está cerrada.
		</before>

		<connection exit="sur" destiny="habitacion-b"></connection>
	</noun>

	<noun names="Habitación B, habitacion-b">
		<after actions="LookAround">
			Estás en la habitación B. Al norte puedes ver una puerta.
		</after>

		<noun names="puerta, porton, puertita, puerta-ba">
			<set>female, fixed, scene, closable, closed</set>

			<after actions="ExamineObject">
				Una puerta de madera que me lleva a otra habitación.
			</after>

			<!-- DESPUÉS de abrir la puerta BA ...-->
			<after actions="OpenObject">
				<!-- ABRIR la puerta AB -->
				<response class="Attr" instance="puerta-ab" unset="closed"></response>
			</after>

			<!-- DESPUÉS de cerrar la puerta BA-->
			<after actions="CloseObject">
				<!-- CERRAR la puerta AB -->
				<response class="Attr" instance="puerta-ab" set="closed"></response>
			</after>
		</noun>

		<!-- El jugador no podrá ir hacia la habitación A estando la puerta cerrada. -->
		<!-- ANTES de ir hacia el norte, CANCELAR ...-->
		<before actions="GoTo" cancel="true">
			<if class="DirectEqualsExit" exit="norte"></if>

			<!-- SI la puerta AB está cerrada-->
			<!-- Se puede consultar cualquiera de las dos puertas a ver si están cerradas.
				Total están sincronizadas. -->
			<if class="IsSet" instance="puerta-ba" attr="closed"></if>

			<!-- Informa que la puerta está cerrada. -->
			La puerta está cerrada.
		</before>

		<connection exit="norte" destiny="habitacion-a"></connection>
	</noun>

</dragonfly>

=== jason80/dragonfly/samples/bosque/naranja.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dragonfly SYSTEM "../../templates/dragonfly.dtd">

<dragonfly>
	<noun names="El Árbol Naranja, arbol-naranja">
		<after actions="LookAround">
			En éste lugar el sendero se curva hacia el este. Y se vuelve por el sur.
			<response class="Message">
				Hay un árbol que destaca de los demás, tiene el tronco naranja.
			</response>
		</after>

		<clone instance="sendero-principal" />

		<noun names="árboles, vegetación, hierba, hierbas">
			<set>plural, fixed, scene</set>
			<after actions="ExamineObject">
				Entre enormes árboles y enmarañada vegetación, es imposible ver y transitar fuera del sendero.
			</after>
		</noun>

		<noun names="árbol, naranja, tronco">
			<set>fixed, scene</set>
			<after actions="ExamineObject">
				El tronco naranja aparece ni bien el sendero se curba hacia el este.
			</after>
		</noun>

		<connection exit="sur" destiny="claro" />
		<connection exit="este" destiny="orilla-rio" />
	</noun>
</dragonfly>

=== jason80/dragonfly/samples/bosque/claro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dragonfly SYSTEM "../../templates/dragonfly.dtd">

<dragonfly>
	<noun names="En Un Claro, claro">

		<after actions="LookAround">
			<if class="IsSet" instance="claro" attr="described" />
			<response class="Message" style="family: 'Sans'; italic: True">
				Algo me huele raro en éste bosque ...
			</response>
		</after>

		<after actions="LookAround">
			Estoy en un claro donde la luz baña totalmente el sendero. Y dicho camino se extiende de sur a norte.
			<response class="Attr" set="described" instance="claro"/>
		</after>

		<!--<noun names="jugador, player"></noun>-->

		<noun names="sendero, camino, sendero-principal">
			<set>fixed, scene</set>
			
			<after actions="ExamineObject">
				La hierba ha dejado de crecer por el angosto sendero. Debe ser bastante transitado.
			</after>
		</noun>

		<noun names="árboles, arboles-principal, arbol, vegetacion, hierba, hierbas, tronco, troncos, madera">
			<set>plural, fixed, scene</set>

			<after actions="ExamineObject">
				Entre enormes árboles y enmarañada vegetación, es imposible ver y transitar fuera del sendero.
			</after>
		</noun>

		<connection exit="norte" destiny="arbol-naranja" />
		<connection exit="sur" destiny="claro" />
	</noun>
</dragonfly>
